# LOCAL MYSQL (DBeaver)

spring.datasource.url=jdbc:mysql://localhost:3306/pennypilot
spring.datasource.username=root
spring.datasource.password=param


spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect